//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 1.6.1.220314.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinRT
{

}